### ISSUE TITLE
Code of Conduct for python-hyper organization, projects, and IRC channel(s)

### ISSUE THREAD

**Issue by sigmavirus24** [python-hyper/documentation#1]
Thoughts about adding [The Contributor Covenant](https://github.com/CoralineAda/contributor_covenant) or something similar for Hyper and friends?

**Comment by Lukasa** [comment]
This is a great idea. I'm going to work on the shell of this tomorrow, and we'll add it.

**Comment by Lukasa** [comment]
Done in 4048da71831bb18927bac5f1a9823c693ec9b043. Thanks!

**Comment by sigmavirus24** [comment]
:+1:
