### ISSUE TITLE
Broken link to the hyper-h2 sub-project on the front page

### ISSUE THREAD

**Issue by alexwlchan** [python-hyper/documentation#9]
The sub-project hyper-h2 link at http://python-hyper.org/en/latest/ points to http://python-hyper.org/h2/.

I get the ReadTheDocs maze if I try to visit that page.

**Comment by Lukasa** [comment]
Yup. This is a known issue, related to rtfd/readthedocs#2235. I'm inclined to want to leave it for the moment as that gives @ericholscher the opportunity to fix it and use that site as a test-case.

**Comment by alexwlchan** [comment]
Seems to be working now.
